// packages/ui/src/components/button.tsx
import type * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@my-monorepo/ui/lib/utils";

const buttonVariants = cva(
	"inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
	{
		variants: {
			variant: {
				default: "bg-primary text-primary-foreground hover:bg-primary/90",
				destructive:
					"bg-destructive text-white hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60",
				outline:
					"border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50",
				secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
				ghost: "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
				link: "text-primary underline-offset-4 hover:underline",
			},
			size: {
				default: "h-9 px-4 py-2 has-[>svg]:px-3",
				sm: "h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5",
				lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
				icon: "size-9",
				"icon-sm": "size-8",
				"icon-lg": "size-10",
			},
		},
		defaultVariants: {
			variant: "default",
			size: "default",
		},
	},
);

function Button({
	className,
	variant = "default",
	size = "default",
	asChild = false,
	...props
}: React.ComponentProps<"button"> &
	VariantProps<typeof buttonVariants> & {
		asChild?: boolean;
	}) {
	const Comp = asChild ? Slot : "button";

	return (
		<Comp
			data-slot="button"
			data-variant={variant}
			data-size={size}
			className={cn(buttonVariants({ variant, size, className }))}
			{...props}
		/>
	);
}

export { Button, buttonVariants };

// packages/ui/src/components/Button.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import type { HTMLButtonAttributes } from "svelte/elements";
	import { cn } from "../lib/classes";

	export type ButtonVariant = "default" | "secondary" | "outline" | "ghost" | "destructive" | "link";
	export type ButtonSize = "default" | "xs" | "sm" | "md" | "lg" | "icon" | "icon-xs" | "icon-sm" | "icon-lg";

	export interface ButtonProps extends HTMLButtonAttributes {
		ref?: HTMLButtonElement | null;
		variant?: ButtonVariant;
		size?: ButtonSize;
		children?: Snippet;
	}

	const base = cn(
		"inline-flex items-center justify-center gap-2",
		"rounded-md font-sans text-sm font-medium",
		"cursor-pointer select-none whitespace-nowrap",
		"focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-background",
		"disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-error aria-invalid:ring-error/20 [&_svg]:pointer-events-none [&_svg]:shrink-0",
	);

	const variants: Record<ButtonVariant, string> = {
		default: "bg-accent text-accent-foreground hover:bg-accent/85",
		secondary: "border border-border bg-muted text-foreground hover:bg-border",
		outline: "border border-border bg-transparent text-foreground hover:bg-muted",
		ghost: "bg-transparent text-foreground hover:bg-muted",
		destructive: "bg-error text-on-dark hover:bg-error/90",
		link: "text-accent underline-offset-4 hover:underline",
	};

	const sizes: Record<ButtonSize, string> = {
		default: "h-9 px-4 text-sm",
		xs: "h-6 px-2 text-xs",
		"icon-xs": "size-6 p-0",
		"icon-sm": "size-8 p-0",
		"icon-lg": "size-10 p-0",
		sm: "h-8 px-3 text-xs",
		md: "h-9 px-4 text-sm",
		lg: "h-10 px-6 text-base",
		icon: "h-9 w-9 p-0",
	};

	let { ref = $bindable(null), variant = "default", size = "default", type = "button", class: className = "", children, ...rest }: ButtonProps = $props();
</script>

<button bind:this={ref} data-slot="button" {type} class={cn(base, variants[variant], sizes[size], className)} {...rest}>
	{@render children?.()}
</button>
