// packages/ui/src/components/input.tsx
import * as React from "react";

import { cn } from "@my-monorepo/ui/lib/utils";

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
	return (
		<input
			type={type}
			data-slot="input"
			className={cn(
				"file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
				"focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
				"aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
				className,
			)}
			{...props}
		/>
	);
}

export { Input };

// packages/ui/src/components/input.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from "svelte/elements";
	import { cn } from "../lib/utils";

	export interface InputProps extends HTMLInputAttributes {
		error?: boolean;
	}

	const base = cn(
		"flex h-9 w-full rounded-md border bg-background px-3 py-1",
		"font-sans text-sm text-foreground placeholder:text-muted-foreground",
		"outline-none transition-colors duration-100",
		"focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-background",
		"disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50",
	);

	let { error, class: className = "", value = $bindable(), ...rest }: InputProps = $props();
</script>

<input
	class={cn(base, error ? "border-error focus-visible:ring-error" : "border-border focus-visible:ring-accent", className)}
	bind:value
	{...rest}
/>
